{% set name = "graphene" %}
{% set version = "2.1.5" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8eee7e2ae9c22d01cf85a43f8c1aeb776a478bc2e20e0ca8d5fb17ba4b9f4767

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - pip
    - python
  run:
    - aniso8601 >=3,<4
    - graphql-core >=2.1,<3
    - graphql-relay >=0.4.5,<1
    - promise >=2.1,<3
    - python
    - six >=1.10.0,<2

test:
  imports:
    - graphene

about:
  home: https://graphene-python.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'GraphQL Framework for Python'
  dev_url: https://github.com/graphql-python/graphene
  doc_url: https://docs.graphene-python.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
    - carlodri
