{% set name = "graphene" %}
{% set version = "2.1.9" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9f2850e064eebfee9a3ef4a1f8aa0742848d97652173ab44c82cc8a62b9ed93

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - six >=1.10.0,<2
    - graphql-core >=2.1,<3
    - graphql-relay >=2,<3
    - aniso8601 >=3,<=7

test:
  imports:
    - graphene

about:
  home: https://graphene-python.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: GraphQL Framework for Python
  dev_url: https://github.com/graphql-python/graphene
  doc_url: https://docs.graphene-python.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
    - carlodri
