{% set name = "graphene" %}
{% set version = "2.1.6" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcbcb24ee960b2c768de4285fbd025aa98eed4ecb6a679bbd41985b05b4008c5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - pip
    - python
  run:
    - aniso8601 >=3,<=6.0
    - graphql-core >=2.1,<3
    - graphql-relay >=0.4.5,<1
    - python
    - six >=1.10.0,<2

test:
  imports:
    - graphene

about:
  home: https://graphene-python.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'GraphQL Framework for Python'
  dev_url: https://github.com/graphql-python/graphene
  doc_url: https://docs.graphene-python.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
    - carlodri
