{% set version = "3.0" %}

package:
  name: graphene
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/graphene/graphene-{{ version }}.tar.gz
  sha256: af48066e152200a071aac1e0b703954c717ec7268720ba190a0c91d9bcb0a122

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - graphql-core >=3.1.2,<3.2
    - graphql-relay >=3,<4
    - aniso8601 >=8,<10

test:
  source_files:
    - graphene/tests
  requires:
    - iso8601 >=0.1,<2
    - mock >=4.0,<5
    - pip
    - promise >=2.3,<3
    - pytest >=5.3,<6
    - pytest-asyncio >=0.10,<2
    - pytest-benchmark >=3.2,<4
    - pytest-cov >=2.8,<3
    - pytest-mock >=2,<3
    - pytz ==2021.1
    - snapshottest >=0.5,<1
  imports:
    - graphene

about:
  home: https://graphene-python.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: GraphQL Framework for Python
  dev_url: https://github.com/graphql-python/graphene
  doc_url: https://docs.graphene-python.org

extra:
  recipe-maintainers:
    - bollwyvl
    - carlodri
