travis:
  secure:
    BINSTAR_TOKEN: SshoDE/yUteuEiCmjySnudSl/uCfsNxwewZU4MzuZMlpqqNmAA9rcnCVgiWexfPFJbmMs1nEIpBSfzSI/DRbFzv3L516Dhw6lN/1oJnRxHQvmfrm4MU3f3Lss9Z7AwxBjL7yEeJvgZSd8Cxyp8dRAwR8rAa/taEXmhXdsXxRF8HDRHoq0Z3HcY4SP9pvVk5RkytFiuboQzTwSCD0lS1Z7b1TtTBLakRf4uKOa0MMB9UOqSKJ2aynqzU35CRfJDTKW+iITfORK14dOhk+bSQ4y8js0dwtNmuIF6ey1+cZFiPk0Qa71xf4utmhTwoZcnJuooKJp4FXngllRl+F+wj8DiZyG+6tqGMfylz7KKCbpE7Cd4gZZgnqny9A7cBHNZlR7urHoPFM7w5rhZD8OoAMpa6mQeVvFoJLYpVgM6Mp/fFtAJGYsgusv2kIUUVF/wgpomqE8qI++p5R5mBwvLt2rXHafgJjTa7kAANMT0NRaaVzpgpaxbK+0MqslMzdD/5YDXyHzEm2hKrUCDIsbS2fu2jnJqFwzn/jXz5Qq2W1D8sTN4seS36coc8uXCETYHwcboUzKthzw5b+kxEizFpY5aSvjnCFBJrY5KpqwfoYqKyrUUlWlgg0QbDHcglI8hYTlVl6Po3/8mHiKQXnnPAA7Tce6BAsg70SEhgw9xKwxnc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
